variables:
  GIT_STRATEGY: none

stages:
  - build
  - test
  - doc

default:
  tags: [rcc,docker,node-01]
  image: continuumio/miniconda3:latest
  before_script:
    - apt-get update > /dev/null
    - export TZ="US/Central"
    - apt-get install -qq make > /dev/null
    - rm -f /etc/localtime
    - cp /usr/share/zoneinfo/$TZ /etc/localtime
    - conda init bash
    - conda create -y --name westpy_env python=3.8
    - source ~/.bashrc
    - conda activate westpy_env
    - pip install -q -U pip
    - pip install -q -U pytest
    - which python

.git_clone: &git_clone
  - rm -rf westpy
  - git clone -b $CI_COMMIT_REF_NAME $CI_REPOSITORY_URL westpy
  - cd westpy
  - git describe --tags --always

westpy_build:
  stage: build
  script:
    - *git_clone
    - pip install .

westpy_test:
  stage: test
  script:
    - *git_clone
    - pip install .
    - cd test-suite
    - pytest

westpy_lint:
  stage: test
  script:
    - pip install -q black
    - *git_clone
    - black --check --diff --color westpy

westpy_doc_build:
  stage: doc
  script:
    - apt-get install -qq pandoc > /dev/null
    - pip install -q -U sphinx
    - pip install -q -U nbsphinx
    - pip install -q -U sphinx_rtd_theme
    - pip install -q -U jupyter
    - *git_clone
    - cd doc
    - make html
    - ls _build/html
