name: Doc

on: [push, pull_request]

jobs:
  doc:
    runs-on: ubuntu-latest
    container: continuumio/miniconda3:latest

    steps:
    - uses: actions/checkout@v3
    - name: Init
      run: |
        apt-get update
        apt-get install -qq make
        apt-get install -qq pandoc
        pip install -q --upgrade pip
        pip install -q nbsphinx
        pip install -q sphinx_rtd_theme
    - name: Build
      run: |
        pip install .
    - name: Doc
      run: |
        cd doc
        make html
